server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceshotel
    username: root
    password: Subbu949166@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
