server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microserviceshotel
    username: postgres
    password: Subbu949166@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8085
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
