server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microserviceshotel
    username: postgres
    password: Subbu949166@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


